package lib.Enums;

public enum guiItems{LOGIN_BUTTON, REGISTER_BUTTON, USERNAME, USERNAME_TEXT,
    PASSWORD, PASSWORD_TEXT, BACK, PASSWORD_2, PASSWORD_2_TEXT, EMAIL, EMAIL_TEXT,
    SHOW, HIDE, REGISTER_TABLE, POP_UP, POP_UP_BUTTON, FRIEND_LIST,FRIEND_SEL_BUTTON,ADD_FRIEND,
    INVITE_FRIEND, MESSAGE_FRIEND, PROFILE_FRIEND, DELETE_FRIEND, NORMAL_BUTTON, RANKED_BUTTON,
    TOURNAMENT_BUTTON, PROFILE_BUTTON, QUIT_BUTTON, YES_BUTTON, NOT_BUTTON, POP_UP_TABLE,
    CONFIRM_ADD_BUTTON, CALCEL_ADD_BUTTON, INTRODUCE_NAME, SEND_MESSAGE,MESSAGE_WRITER, CHAT,
    QUIT_YES, QUIT_NO, LOG_OUT_YES, LOG_OUT_NO}