package lib.Enums;

//Tipos de elementos que se van a imprimir por pantalla
public enum Item_Type {
    NONE,
    SCENARY_1, SCENARY_2,
    PLAYER, ENEMY,
    PLAYERTHROWABLE, ENEMYTHROWABLE,
    MENU, SURE,
    TIMER1, TIMER2, TIMERFRAME,
    HPBAR1, HPBAR2,
    NAME1, NAME2,
    INDICATOR1, INDICATOR2,
    BUBBLE1, BUBBLE2, BUBBLE3, BUBBLE4,
    ANNOUNCEMENT,
    P1_SELECT, P2_SELECT, P1_MUG, P2_MUG, P1_NAME, P2_NAME,
    BONUS, SCORE_FRAME,
    SCORE_TEXT, SCOREN1, SCOREN2, SCOREN3, SCOREN4, SCOREN5,
    LIFE_TEXT, LIFEN1, LIFEN2, LIFEN3, LIFEN4, LIFEN5,
    TIME_TEXT, TIMEN1, TIMEN2, TIMEN3, TIMEN4, TIMEN5,
    TOTAL_TEXT, TOTALN1, TOTALN2, TOTALN3, TOTALN4, TOTALN5,
}

