package lib.Enums;

// Tipos de movimientos de un personaje
public enum Movement {
    NONE, SOFT_PUNCH, SOFT_KICK, HARD_PUNCH, HARD_KICK, STANDING_BLOCK, CROUCHED_BLOCK,
    NORMAL_JUMP, JUMP_ROLL_RIGHT, CROUCHED_WALKING, THROW, STANDING, WALKING, WALKING_BACK,
    CROUCH, UNDO_CROUCH, CROUCH_2, ATTACK_POKE, ROLL_FRONT, THROWN_OUT,
    SOFT_KNOCKBACK, MEDIUM_KNOCKBACK, HARD_KNOCKBACK, CROUCHED_KNOCKBACK, STANDING_BLOCK_KNOCKBACK_SOFT,
    STANDING_BLOCK_KNOCKBACK_HARD, JUMP_KNOCKBACK, JUMP_PUNCH_DOWN, JUMP_ROLL_PUNCH_DOWN, JUMP_FALL, JUMP_ROLL_FALL,
    ATTACK, DEFENSE, RUN_AWAY, GETTING_CLOSER, GLOBAL,
    CROUCHING_HARD_PUNCH, CROUCHING_SOFT_PUNCH, HOOK, CROUCHING_HARD_KICK, CROUCHING_SOFT_KICK, DASH, CROUCHED_BLOCK_KNOCKBACK,
    CHARGED_PUNCH_A, CHARGED_PUNCH_C, JUMP_KICK_DOWN, JUMP_KICK, JUMP_ROLL_HARD_PUNCH_DOWN, JUMP_HARD_PUNCH_DOWN,
    VICTORY_ROUND, VICTORY_FIGHT, DEFEAT,
    REVERSE_KICK_B, REVERSE_KICK_D, JUMP_ROLL_LEFT, SPIN_PUNCH_A, SPIN_PUNCH_C
}
