package lib.Enums;

public enum Movement {
    NONE, SOFT_PUNCH, SOFT_KICK, HARD_PUNCH, HARD_KICK, STANDING_BLOCK, CROUCHED_BLOCK,
    NORMAL_JUMP, CROUCHED_WALKING, QUICK_BACK, GUARD_ATTACK, HARD_KNOCK, PLANE_CHANGE,
    JOKE, THROW, CHARGE, DESPERATION_MOVE, STANDING, STANDING_2, WALKING, WALKING_BACK,
    CROUCH, CROUCH_2, ATTACK_POKE, ROLL_FRONT
}
