package lib.Enums;

// Elementos seleccionables en los menús
public enum Selectionable {
    NONE, START, PRINCIPAL_GAME, PRINCIPAL_OPTIONS, PRINCIPAL_RANK, PRINCIPAL_EXIT,
    GAME_HISTORY, GAME_MULTIPLAYER, GAME_IA, ESCAPE_RESUME,
    ESCAPE_BACK, ESCAPE_EXIT, MAP_USA, MAP_AUS, MAP_CHI
}
