package lib.objects.networking.gui;

public enum guiItems{LOGIN_BUTTON, REGISTER_BUTTON, USERNAME, USERNAME_TEXT,
    PASSWORD, PASSWORD_TEXT, BACK, PASSWORD_2, PASSWORD_2_TEXT, EMAIL, EMAIL_TEXT,
    SHOW, HIDE, REGISTER_TABLE, POP_UP, POP_UP_BUTTON, FRIEND_LIST,FRIEND_SEL_BUTTON,ADD_FRIEND,
    INVITE_FRIEND, MESSAGE_FRIEND, PROFILE_FRIEND, DELETE_FRIEND, NORMAL_BUTTON, RANKED_BUTTON,
    RANKING_BUTTON, PROFILE_BUTTON, QUIT_BUTTON, YES_BUTTON, NOT_BUTTON, POP_UP_TABLE,
    CONFIRM_ADD_BUTTON, CANCEL_ADD_BUTTON, INTRODUCE_NAME, SEND_MESSAGE,MESSAGE_WRITER, CHAT,
    QUIT_YES, QUIT_NO, LOG_OUT_YES, LOG_OUT_NO, CLOSE_CHAT, HISTORIAL, PROFILE_NAME, PROFILE_NORMALS,
    PROFILE_RANKEDS, PROFILE_POINTS, HISTORIAL2, SELECT_TERRY, SELECT_MAI,SELECT_ANDY, TERRY_MUG,
    ANDY_MUG, MAI_MUG, TERRY_COMBOS, ANDY_COMBOS, MAI_COMBOS, UNKNOWN_MUG, TIMER, SELECT_AUSTRALIA,
    SELECT_CHINA, SELECT_USA, USA_MAP, CHINA_MAP, AUSTRALIA_MAP, ACCEPT_FRIEND, REJECT_FRIEND,
    CONFIRM_DELETE, CANCEL_DELETE, AUXILIAR_BACKGROUND, CANCEL_SEARCH_GAME, CANCEL_SEARCH_RANK_GAME,
    LOADING, CLOSE_GAME, FRIEND_REQUEST_NOTIFICATION,PENDING_MESSAGES_NOTIFICATION, VERIFY_BUTTON,
    INTRODUCE_CODE, BAD_CODE, RECOVER_BUTTON, CHANGE_PASS_BUTTON, CONFIRM_CHANGE_PASS, OLD_PASS,
    NEW_PASS, NEW_PASS_REPEAT, OLD_PASS_TEXT, NEW_PASS_TEXT, NEW_PASS_REPEAT_TEXT, CANCEL_CHANGE_PASS,
    VERIFY_POP_BUTTON, RIVAL_USERNAME, CANCEL_FRIEND_CHALLENGE, ACCEPT_FRIEND_CHALLENGE,
    REJECT_FRIEND_CHALLENGE, OKEY_INVITATION_CANCELLED, RANKING, RETRY_CONNECTION, PLAYER_1_CHAR,
    PLAYER_2_CHAR, PLAYER_USERNAME, GAME_RESULT, RANK_POINTS, CONFIRM_END_GAME}